FORMAT: 1A
HOST: https://api.example.com/v1

# Mail API

Contact us mail API for the Black Puppy website

# Group Healthcheck

This section describes the features for checking the health of the service

## HealthCheck [/mail/healthcheck]

### Check the health of the application [GET]

+ Response 200 (application/json)

  + Body
    {"StatusMessage":"Hello World"}


# Group Mail

This section describes about the sending mail

## ContactUs [/mail/contactus]

Send a contact us mail

### Send Contact Us mail [POST]

+ Request (application/json)
  {
    "name": "your name",
    "email_address": "nic@hisaddress.com",
    "message": "The message to send"
  }

+ Response 200 (application/json)

  + Body
    {
      "message":"ok"
    }
